# API fetching settings
db_path: "database_alumnos"
db_name: "alumnos.sqlite"
checkpoint_name: "checkpoint.json"
batch_size: 1000
api_limit: 10000
total_records: 2000000
total_api_calls: 0
total_records_fetched: 0
total_records_inserted: 0

